
#pragma once


/**
    Doxygen documentation is automatically added to your python objects
    when the bindings are autogenerated.
*/
class __attribute__((visibility("default"))) DemoClass {
public:
    virtual ~DemoClass() = default;

    /** Sets X */
    virtual void setX(int x) {
        m_x = x;
    }

    /** Gets X */
    int getX() const {
        return m_x;
    }

protected:
    int m_x = 0;
};
