
#pragma once

#include <demo.h>

/**
    Doxygen documentation is automatically added to your python objects
    when the bindings are autogenerated.
*/
class DemoChild : public DemoClass {
public:

    /** Sets X */
    void setX(int x) override;

};
