---
name: test

on:
  pull_request:
  push:
    branches:
    - main
    tags:
    - '*'

jobs:

  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install build
      shell: bash
      run: python -m pip --disable-pip-version-check install build

    - name: Build sdist + wheel
      shell: bash
      run: python -m build producer

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: producer/dist
